version: '3'
services:
  demo-backend:
    container_name: demo-backend
    build:
      dockerfile: ./Dockerfile
    ports:
      - "4000:80"
    depends_on: 
      - test
  test:
    image: nvidia/cuda:10.2-base
    command: nvidia-smi
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: 1
            capabilities: [gpu, utility]